# Generated by Django 5.2.1 on 2025-07-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('telephone_number', models.PositiveSmallIntegerField(verbose_name='Numero telefonico')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
