# Generated by Django 5.2.1 on 2025-07-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telephone_number',
            field=models.CharField(max_length=10, verbose_name='Numero telefonico'),
        ),
    ]
