# Generated by Django 5.2.1 on 2025-07-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_empleado_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contador'), ('1', 'Aadministrador'), ('2', 'Economista'), ('3', 'Desarrollador'), ('4', 'Jefe de turno'), ('5', 'Jefe de plaza'), ('6', 'Cajero'), ('7', 'Director de tramo'), ('8', 'Analista liquidador'), ('9', 'Monitorista'), ('10', 'Otro')], max_length=2, verbose_name='Trabajo'),
        ),
    ]
