# Generated by Django 5.2.1 on 2025-07-11 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depart_productos', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.PositiveIntegerField(unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cost', models.FloatField(verbose_name='Precio')),
                ('expiration_date', models.DateField(verbose_name='Fecha de caducidad')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Descripcion')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depart_productos.departamentoproductos', verbose_name='Departamento productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
