# Generated by Django 5.2.1 on 2025-07-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=20, verbose_name='SKU'),
        ),
    ]
