# Generated by Django 5.2.1 on 2025-07-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('shor_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nombre corto')),
                ('anulate', models.BooleanField(default=False, verbose_name='Anulado')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas de la empresa',
                'ordering': ['name'],
                'unique_together': {('name', 'shor_name')},
            },
        ),
    ]
